### ISSUE TITLE
Fix matrix multiplication

### ISSUE THREAD

**Issue by binarman** [ROCmSoftwarePlatform/triton#187]
## Main issue

On branch from #180 matrix multiplication from tutorial section [python/tutorials/03-matrix-multiplication.py](https://github.com/ROCmSoftwarePlatform/triton/blob/14af4c0e3abcc783c3fabfad145c7bcb5a50767e/python/tutorials/03-matrix-multiplication.py) is broken.

This branch is going to be merged soon, so lets work on fix in advance.

There are at least two problems:

1. LDS size is not taken into account
2. Triton generates `cp.async.commit_group` instructions that are not supported by amd gpu backend, if simply remove generation of these instructions, large error is produced.

## Related problems

1. `triton.ops.mutmul` implementation uses autotuner, which is not working with AMD hardware.
It fails with following error:
<details>
<summary> stack trace </summary>

```
  File "/home/aefimov/triton/python/triton/runtime/autotuner.py", line 90, in run
    return self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **kwargs, **config.kwargs)
  File "<string>", line 43, in matmul_kernel
  File "/home/aefimov/triton/python/triton/compiler.py", line 2076, in __getattribute__
    self._init_handles()
  File "/home/aefimov/triton/python/triton/compiler.py", line 2060, in _init_handles
    raise OutOfResources(self.shared, max_shared, "shared memory")
triton.compiler.OutOfResources: out of resource: shared memory, Required: 98304, Hardware limit: 65536. Reducing block sizes or `num_stages` may help.
rocm-user@aefimov-pc:/home/aefimov/triton/python (triton-mlir)$ python3 ./tutorials/03-matrix-multiplication.py
/tmp/tmpfkn4kdha/main.c:2:18: fatal error: cuda.h: No such file or directory
    2 |         #include <cuda.h>
      |                  ^~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "./tutorials/03-matrix-multiplication.py", line 292, in <module>
    triton_output = triton.ops.matmul(a, b)
  File "/home/aefimov/triton/python/triton/ops/matmul.py", line 148, in forward
    return _matmul._call(a, b)
  File "/home/aefimov/triton/python/triton/ops/matmul.py", line 139, in _call
    _kernel[grid](a, b, c, M, N, K,
  File "/home/aefimov/triton/python/triton/runtime/autotuner.py", line 75, in run
    pruned_configs = self.prune_configs(kwargs)
  File "/home/aefimov/triton/python/triton/runtime/autotuner.py", line 95, in prune_configs
    pruned_configs = self.early_config_prune(self.configs, self.nargs)
  File "/home/aefimov/triton/python/triton/ops/matmul_perf_model.py", line 116, in early_config_prune
    triton.compiler.init_cuda_utils()
  File "/home/aefimov/triton/python/triton/compiler.py", line 2248, in init_cuda_utils
    cuda_utils = CudaUtils()
  File "/home/aefimov/triton/python/triton/compiler.py", line 2234, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/home/aefimov/triton/python/triton/compiler.py", line 1656, in _build
    ret = subprocess.check_call([cc, src, f"-I{hip_include_dir}", f"-I{py_include_dir}", f"-I{srcdir}", "-shared", "-fPIC", f"-L{hip_lib_dir}", "-lamdhip64", "-o", so])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpfkn4kdha/main.c', '-I/opt/rocm/include', '-I/usr/include/python3.8', '-I/tmp/tmpfkn4kdha', '-shared', '-fPIC', '-L/opt/rocm/lib', '-lamdhip64', '-o', '/tmp/tmpfkn4kdha/cuda_utils.cpython-38-x86_64-linux-gnu.so']' returned non-zero exit status 1.
```

</details>

2. `triton.ops.matmul` autotuner do not take into account LDS on AMD hardware too.

Main goal of this issue is fixing tutotial and triton pipeline, so `03-matrix-multiplication.py` run succeeds.
Other mentioned problems are optional at this point (could be considered as a standalone tasks in the future, if they turn out to be big).

**Comment by jayfurmanek** [comment]
found this older issue - assigning it for now so I don't lose track of it since its over in the triton repo and doesn't have access to the tags.

**Comment by binarman** [comment]
Not needed anymore, this issue is outdated
