### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by lzxdn** [ROCmSoftwarePlatform/triton#290]
I tried to compile the latest trion-mlir branch on centos7.6. When I import triton, the following error occurs.
```>>> import triton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/tengfei/triton/triton/python/triton/__init__.py", line 8, in <module>
    from .runtime import (
  File "/public/home/tengfei/triton/triton/python/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, OutOfResources, autotune,
  File "/public/home/tengfei/triton/triton/python/triton/runtime/autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "/public/home/tengfei/triton/triton/python/triton/testing.py", line 7, in <module>
    from ._C.libtriton.triton import runtime
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /public/home/tengfei/triton/triton/lib/rocm/libhsa-runtime64.so.1)
```
It seems that the glbc version of the system is too low. I've tried different solutions but without success.

**Comment by binarman** [comment]
Good day!
Did you try to copy `libhsa-runtime64.so.1` from your local rocm distribution?
it is probably located somewhere in `/opt/rocm/lib/`
