### ISSUE TITLE
argmax tl.reduce gives `error: 'tt.reduce' op failed to infer returned types`

### ISSUE THREAD

**Issue by jataylo** [ROCmSoftwarePlatform/triton#364]
@jayfurmanek @zhanglx13 @binarman 
cc: @dllehr-amd @jithunnair-amd 

With TOT triton we are seeing a UT regression in PyTorch.

I have confirmed the change that caused the breakage came in during ifu230908-2 and last known working commit is https://github.com/ROCmSoftwarePlatform/triton/commit/287b0adcc2a9607b326a0cda18388dd221c386c2

The UTs failing in `test_torchinductor.py` are all argmax related
```
CudaTests.test_argmax_argmin2_cuda
CudaTests.test_argmax_argmin_with_nan_cuda
CudaTests.test_reduction4_cuda
```

I have developed a reproducer that passes on NVIDIA platform with latest triton (29828fe), fails on TOT triton-mlir and passes on triton-mlir at commit https://github.com/ROCmSoftwarePlatform/triton/commit/287b0adcc2a9607b326a0cda18388dd221c386c2.

Note: the failure occurs on the store after the `max_with_index` reduction.
`return tl.reduce((value, index), dim, maximum_with_index)`

**Reproducer**
```
import torch
import triton
import triton.language as tl

@triton.jit
def min_with_index(value, index, dim):
    return tl.reduce((value, index), dim, minimum_with_index)

@triton.jit
def max_with_index(value, index, dim):
    return tl.reduce((value, index), dim, maximum_with_index)

@triton.jit
def promote_to_tensor(x):
    # Addition promotes to tensor for us
    return x + tl.zeros((1,), tl.int1)

@triton.jit
def is_floating(x):
    return promote_to_tensor(x).dtype.is_floating()

@triton.jit
def maximum_with_index(a_value, a_index, b_value, b_index):
    mask = a_value > b_value
    equal = a_value == b_value
    if is_floating(a_value):
        a_isnan = a_value != a_value
        b_isnan = b_value != b_value
        mask |= a_isnan and not b_isnan
        # Consider NaNs as equal
        equal |= a_isnan and b_isnan

    # Prefer lowest index if values are equal
    mask |= equal & (a_index < b_index)
    return tl.where(mask, a_value, b_value), tl.where(mask, a_index, b_index)

@triton.jit
def minimum_with_index(a_value, a_index, b_value, b_index):
    mask = a_value < b_value
    equal = a_value == b_value
    if is_floating(a_value):
        a_isnan = a_value != a_value
        b_isnan = b_value != b_value
        mask |= a_isnan and not b_isnan
        # Consider NaNs as equal
        equal |= a_isnan and b_isnan

    # Prefer lowest index if values are equal
    mask |= equal & (a_index < b_index)
    return tl.where(mask, a_value, b_value), tl.where(mask, a_index, b_index)

@triton.jit
def triton_kernel(in_ptr0, out_ptr0, out_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 144
    rnumel = 144
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rbase = tl.arange(0, RBLOCK)[None, :]
    x0 = xindex
    _tmp2 = tl.full([XBLOCK, RBLOCK], float("-inf"), tl.float32)
    _tmp2_index = tl.full([XBLOCK, RBLOCK], 9223372036854775807, tl.int64)
    _tmp3 = tl.full([XBLOCK, RBLOCK], float("inf"), tl.float32)
    _tmp3_index = tl.full([XBLOCK, RBLOCK], 9223372036854775807, tl.int64)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r1 = rindex
        tmp0 = tl.load(in_ptr0 + (x0 + (144*r1)), rmask & xmask, eviction_policy='evict_first', other=0).to(tl.float32)
        tmp1 = tl.broadcast_to(tmp0, [XBLOCK, RBLOCK])
        _tmp2_next, _tmp2_index_next = maximum_with_index(
            _tmp2, _tmp2_index, tmp1, rindex
        )
        _tmp2 = tl.where(rmask & xmask, _tmp2_next, _tmp2)
        _tmp2_index = tl.where(rmask & xmask, _tmp2_index_next, _tmp2_index)
        _tmp3_next, _tmp3_index_next = minimum_with_index(
            _tmp3, _tmp3_index, tmp1, rindex
        )
        _tmp3 = tl.where(rmask & xmask, _tmp3_next, _tmp3)
        _tmp3_index = tl.where(rmask & xmask, _tmp3_index_next, _tmp3_index)
    _, tmp2_tmp = max_with_index(_tmp2, _tmp2_index, 1)
    tmp2 = tmp2_tmp[:, None]
    tl.store(out_ptr0 + (x0), tmp2, xmask)

arg0_1 = torch.rand((144, 144), device='cuda:0', dtype=torch.float16)
buf0 = torch.empty((144, ), device='cuda', dtype=torch.int64)
buf1 = torch.empty((144, ), device='cuda', dtype=torch.int64)
xnumel = 144
rnumel = 144

# Launch the triton kernel without async compile
triton_kernel[(144,)](arg0_1, buf0, buf1, 144, 144, 256, 256)
```

Full error log:
```
loc(callsite("kernel.py":13:42 at "kernel.py":83:53)): error: 'tt.reduce' op inferred type(s) 'tensor<256xf32, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>', 'tensor<256xi64, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>' are incompatible with return type(s) of operation 'tensor<256xf32, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [8, 1], threadsPerWarp = [32, 2], warpsPerCTA = [1, 4], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>', 'tensor<256xi64, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>'
loc(callsite("kernel.py":13:42 at "kernel.py":83:53)): error: 'tt.reduce' op failed to infer returned types
Traceback (most recent call last):
  File "kernel.py", line 95, in <module>
    triton_kernel[(144,)](arg0_1, buf0, buf1, 144, 144, 256, 256)
  File "<string>", line 74, in triton_kernel
  File "/root/triton/python/triton/compiler/compiler.py", line 607, in compile
    next_module = compile_kernel(module)
  File "/root/triton/python/triton/compiler/compiler.py", line 507, in <lambda>
    lambda src: optimize_ttgir(ttir_to_ttgir(src, num_warps, warp_size, num_ctas, arch), num_stages, num_warps, num_ctas, arch, cluster_info, enable_warp_specialization, enable_persistent, optimize_epilogue))
  File "/root/triton/python/triton/compiler/compiler.py", line 154, in optimize_ttgir
    pm.run(mod)
```

**Comment by jataylo** [comment]
@oplavsic is this related to https://github.com/ROCmSoftwarePlatform/triton/issues/236 at all? I'm guessing this is a different issue as the last working commit was after you raised this

**Comment by jayfurmanek** [comment]
It does look similar to #236 . We'll take a look

**Comment by oplavsic** [comment]
@jataylo I don't think this is related to #236. This issue is raised long time ago, before we even had reduce algorithm working in mfma layout.

**Comment by alefimov-amd** [comment]
If I understand correctly, this error is a result of incorrect work of `RemoveLayoutConversion` pass.

First `Coalesce` pass creates coalesced layout for load operations, then `RemoveLayoutConversion` propagates it down to reduce operation and inside it's body, but do not change overall layout or reduce op.

**Comment by alefimov-amd** [comment]
draft PR #372

**Comment by jayfurmanek** [comment]
Determine why upstream works

**Comment by binarman** [comment]
upstream works because of this change in heuristic that applies transformation:

https://github.com/openai/triton/commit/3a848e272930bf04f5cf2db7269b1035b4742c89#diff-00e5b15068049beb083ce4359833adf047e65d36691c575685a5995277ff26c6R932

**Comment by binarman** [comment]
I managed to create mlir that crashes upstream, but I am not sure if it is possible to get it from triton source level.

I think we should proceed with upstream fix and I'll continue some discussion in upstream.

**Comment by binarman** [comment]
Here is some other test that is currently failing :slightly_frowning_face: 
It is minimal reproducer that I was able to extract from example that @jataylo provided.
And it works in upstream.

<details>

<summary>reproducer</summary>

``` mlir
#blocked = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [2, 2], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>
#blocked2 = #triton_gpu.blocked<{sizePerThread = [1], threadsPerWarp = [64], warpsPerCTA = [4], order = [0], CTAsPerCGA = [1], CTASplitNum = [1], CTAOrder = [0]}>
module attributes {"triton_gpu.compute-capability" = 0 : i32, "triton_gpu.num-ctas" = 1 : i32, "triton_gpu.num-warps" = 4 : i32, "triton_gpu.threads-per-warp" = 64 : i32} {
  tt.func public @triton_kernel(%arg0: !tt.ptr<f32, 1> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32, 1> {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %cst_5 = arith.constant dense<1> : tensor<128x1xi1, #blocked>
    %cst_7 = arith.constant dense<1> : tensor<128x4xi1, #blocked>
    %cst_8 = arith.constant dense<128> : tensor<128x1xi32, #blocked>
    %cst_9 = arith.constant dense<1.1> : tensor<128x1xf32, #blocked>

    %2 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #triton_gpu.slice<{dim = 1, parent = #blocked2}>>
    %4 = tt.expand_dims %2 {axis = 1 : i32} : (tensor<128xi32, #triton_gpu.slice<{dim = 1, parent = #blocked2}>>) -> tensor<128x1xi32, #blocked2>
    %5 = triton_gpu.convert_layout %4 : (tensor<128x1xi32, #blocked2>) -> tensor<128x1xi32, #blocked>
    %18 = tt.splat %arg0 : (!tt.ptr<f32, 1>) -> tensor<128x4x!tt.ptr<f32, 1>, #blocked>
    %24 = triton_gpu.convert_layout %18 : (tensor<128x4x!tt.ptr<f32, 1>, #blocked>) -> tensor<128x4x!tt.ptr<f32, 1>, #blocked2>
    %25 = triton_gpu.convert_layout %cst_7 : (tensor<128x4xi1, #blocked>) -> tensor<128x4xi1, #blocked2>
    %27 = tt.load %24, %25 {cache = 1 : i32, evict = 1 : i32, isVolatile = false} : tensor<128x4xf32, #blocked2>
    %28 = triton_gpu.convert_layout %27 : (tensor<128x4xf32, #blocked2>) -> tensor<128x4xf32, #blocked>
    %48 = tt.splat %arg1 : (!tt.ptr<f32, 1>) -> tensor<128x1x!tt.ptr<f32, 1>, #blocked>
    %49 = tt.addptr %48, %5 : tensor<128x1x!tt.ptr<f32, 1>, #blocked>, tensor<128x1xi32, #blocked>
    %52 = tt.load %49, %cst_5 {cache = 1 : i32, evict = 3 : i32, isVolatile = false} : tensor<128x1xf32, #blocked>
    %56:1 = "tt.reduce"(%28) <{axis = 1 : i32}> ({
    ^bb0(%arg2: f32, %arg3: f32):
      tt.reduce.return %arg3 : f32
    }) : (tensor<128x4xf32, #blocked>) -> (tensor<128xf32, #triton_gpu.slice<{dim = 1, parent = #blocked}>>)
    %60 = tt.expand_dims %56#0 {axis = 1 : i32} : (tensor<128xf32, #triton_gpu.slice<{dim = 1, parent = #blocked}>>) -> tensor<128x1xf32, #blocked>
    %74 = arith.addf %60, %52 : tensor<128x1xf32, #blocked>
    tt.store %48, %74 {cache = 1 : i32, evict = 1 : i32} : tensor<128x1xf32, #blocked>
    tt.return
  }
}
```

</details>

**Comment by jataylo** [comment]
> Here is some other test that is currently failing 🙁 It is minimal reproducer that I was able to extract from example that @jataylo provided. And it works in upstream.

To clarify we only observe this later failure after bringing in @binarman 's  draft PR fix https://github.com/ROCmSoftwarePlatform/triton/pull/377. Perhaps some other change from upstream is needed also.
